"use client";

import React from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Info, Coins, ShieldAlert, Award, TrendingUp } from "lucide-react";

export interface StakingPositionData {
  staked: string;
  claimable: string;
  warming: string;
  cooling: string;
}

interface PositionCardProps {
  position: StakingPositionData | null;
  platformTotalStaked?: string;
  currentApy?: number;
}

export function formatUsdc(val: string | number | undefined | null): string {
  if (val === undefined || val === null || val === "") return "0.000000";
  const num = typeof val === "string" ? parseFloat(val) : val;
  if (isNaN(num)) return "0.000000";
  return num.toLocaleString("en-US", {
    minimumFractionDigits: 6,
    maximumFractionDigits: 6,
  });
}

export function PositionCard({
  position,
  platformTotalStaked = "15840250.000000",
  currentApy = 18.5,
}: PositionCardProps) {
  return (
    <div className="space-y-6">
      {/* Premium Hero Stats Bar */}
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
        {/* Platform Total Staked */}
        <Card className="relative overflow-hidden border-2 border-foreground/10 bg-gradient-to-br from-card to-muted shadow-sm hover:shadow-md transition-all duration-300">
          <div className="absolute top-0 right-0 p-3 opacity-10">
            <Coins className="h-20 w-20 text-foreground" />
          </div>
          <CardHeader className="pb-2">
            <CardDescription className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
              Platform Total Staked
            </CardDescription>
            <CardTitle className="font-mono text-xl sm:text-2xl font-black text-foreground">
              {formatUsdc(platformTotalStaked)}
              <span className="ml-1 text-xs font-bold text-muted-foreground">USDC</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-xs text-muted-foreground">Total network liquidity pool</p>
          </CardContent>
        </Card>

        {/* Dynamic APY */}
        <Card className="relative overflow-hidden border-2 border-primary/20 bg-gradient-to-br from-card to-primary/5 shadow-sm hover:shadow-md transition-all duration-300">
          <div className="absolute top-0 right-0 p-3 opacity-10">
            <TrendingUp className="h-20 w-20 text-primary" />
          </div>
          <CardHeader className="pb-2">
            <CardDescription className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
              Current APY
              <TooltipProvider>
                <Tooltip delayDuration={100}>
                  <TooltipTrigger asChild>
                    <button type="button" className="text-muted-foreground hover:text-foreground focus:outline-none">
                      <Info className="h-3.5 w-3.5" />
                    </button>
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs border border-foreground/10 bg-card p-3 shadow-md rounded-lg">
                    <p className="text-xs leading-relaxed text-card-foreground">
                      Staking APY is dynamically computed based on the volume of NGN financing deals active on the platform. Stakers receive a proportional share of the interest generated by financing platform float.
                    </p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </CardDescription>
            <CardTitle className="font-mono text-xl sm:text-2xl font-black text-primary flex items-baseline">
              {currentApy.toFixed(2)}%
              <span className="ml-1 text-xs font-bold text-primary/80 uppercase">Var</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-xs text-muted-foreground">Interest dynamically compounded</p>
          </CardContent>
        </Card>

        {/* Your Staked Balance */}
        <Card className="relative overflow-hidden border-2 border-foreground/10 bg-gradient-to-br from-card to-muted shadow-sm hover:shadow-md transition-all duration-300">
          <div className="absolute top-0 right-0 p-3 opacity-10">
            <Award className="h-20 w-20 text-foreground" />
          </div>
          <CardHeader className="pb-2">
            <CardDescription className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Your Staked Balance
            </CardDescription>
            <CardTitle className="font-mono text-xl sm:text-2xl font-black text-foreground">
              {position ? formatUsdc(position.staked) : "0.000000"}
              <span className="ml-1 text-xs font-bold text-muted-foreground">USDC</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-xs text-muted-foreground">Actively earning rewards</p>
          </CardContent>
        </Card>

        {/* Claimable Rewards */}
        <Card className="relative overflow-hidden border-2 border-foreground/10 bg-gradient-to-br from-card to-muted shadow-sm hover:shadow-md transition-all duration-300">
          <div className="absolute top-0 right-0 p-3 opacity-10">
            <Award className="h-20 w-20 text-emerald-500" />
          </div>
          <CardHeader className="pb-2">
            <CardDescription className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Claimable Rewards
            </CardDescription>
            <CardTitle className="font-mono text-xl sm:text-2xl font-black text-emerald-600 dark:text-emerald-500">
              {position ? formatUsdc(position.claimable) : "0.000000"}
              <span className="ml-1 text-xs font-bold text-emerald-600 dark:text-emerald-500">USDC</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-xs text-muted-foreground">Available to claim instantly</p>
          </CardContent>
        </Card>
      </div>

      {/* Stake Composition Breakdown */}
      {position && (Number(position.warming) > 0 || Number(position.cooling) > 0) && (
        <Card className="border-2 border-foreground/10 bg-muted/40 shadow-sm overflow-hidden">
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-sm font-bold text-foreground">Staking Composition</CardTitle>
                <CardDescription className="text-xs">
                  Breakdown of active, warming, and cooling assets
                </CardDescription>
              </div>
              <TooltipProvider>
                <Tooltip delayDuration={100}>
                  <TooltipTrigger asChild>
                    <button type="button" className="text-muted-foreground hover:text-foreground">
                      <Info className="h-4 w-4" />
                    </button>
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs border border-foreground/10 bg-card p-3 shadow-md rounded-lg text-xs space-y-1.5">
                    <p><strong>Active:</strong> Tokens locked and generating dynamic yields.</p>
                    <p><strong>Warming:</strong> Tokens awaiting confirmation or the start of a yield cycle.</p>
                    <p><strong>Cooling:</strong> Unstaked tokens waiting out the lock withdrawal countdown.</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <div className="flex h-3.5 w-full overflow-hidden rounded-full bg-foreground/10 font-mono text-sm font-bold">
                <div
                  style={{
                    width: `${
                      (Number(position.staked) /
                        (Number(position.staked) +
                          Number(position.warming) +
                          Number(position.cooling) || 1)) *
                      100
                    }%`,
                  }}
                  className="bg-primary transition-all duration-500"
                  title={`Active: ${formatUsdc(position.staked)}`}
                />
                <div
                  style={{
                    width: `${
                      (Number(position.warming) /
                        (Number(position.staked) +
                          Number(position.warming) +
                          Number(position.cooling) || 1)) *
                      100
                    }%`,
                  }}
                  className="bg-amber-500 transition-all duration-500"
                  title={`Warming: ${formatUsdc(position.warming)}`}
                />
                <div
                  style={{
                    width: `${
                      (Number(position.cooling) /
                        (Number(position.staked) +
                          Number(position.warming) +
                          Number(position.cooling) || 1)) *
                      100
                    }%`,
                  }}
                  className="bg-destructive/60 transition-all duration-500"
                  title={`Cooling: ${formatUsdc(position.cooling)}`}
                />
              </div>

              <div className="grid grid-cols-3 gap-4">
                <div className="rounded-lg border border-foreground/10 bg-card p-2.5 text-center">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
                    Active
                  </p>
                  <p className="font-mono text-sm font-black text-foreground">
                    {formatUsdc(position.staked)}
                  </p>
                </div>
                <div className="rounded-lg border border-foreground/10 bg-card p-2.5 text-center">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
                    Warming
                  </p>
                  <p className="font-mono text-sm font-black text-amber-600 dark:text-amber-500">
                    {formatUsdc(position.warming)}
                  </p>
                </div>
                <div className="rounded-lg border border-foreground/10 bg-card p-2.5 text-center">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
                    Cooling
                  </p>
                  <p className="font-mono text-sm font-black text-destructive">
                    {formatUsdc(position.cooling)}
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
